### ISSUE TITLE
error : the argument type 'theme' is from 'package: pdf/widgets.dart

### ISSUE THREAD

**Issue by arabianco** [KevinPatel04/Far-From-Home#10]
error : the argument type 'theme' is from 'package: pdf/widgets.dart

**Comment by KevinPatel04** [comment]
@arabianco It must be an issue with version compatibility. When I developed the application flutter was just released after that many stable version has been released.
One of the GitHub contributors has put effort to upgrade the version to Flutter 2.0. I have merged that pull request you can try with the current version and check if it works.
